### PR TITLE
fix: remove extraneous prefix completion items

### LINKED ISSUE #97: Extraneous namespace prefix completion item
Namespace completion item is provided for all namespace prefixes that are available in given context even though there are no applicable elements for the given namespace.

Simple schema:
```json
{
  "name": "Edmx",
  "namespace": "http://docs.oasis-open.org/odata/ns/edmx",
  "cardinality": "single",
  "required": true,
  "require": true,
  "attributesType": "closed",
  "elementsType": "closed",
  "elements": {
    "Example": {
      "name": "Example",
      "namespace": "http://docs.oasis-open.org/odata/ns/edm",
      "cardinality": "many",
      "required": false,
      "attributesType": "closed",
      "elementsType": "closed",
      "attributes": {
        "Uri": {
          "key": "Uri",
          "required": true
        }
      }
    }
  }
}

```
XML document
```xml
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
    <|
</edmx:Edmx>
```
Cursor position is denoted with `|` symbol. If code completion is triggered there, then there will be a completion item for `edmx` namespace prefix, even though it can not contain any elements from that namespace.

### PR DESCRIPTION
**Pull request by voicis**
Fixes #97.

Added more strenuous checks for namespace prefixes. 

Namespace prefix completion item now should only appear when schema allows elements from that namespace in the given context, including cardinality checks for existing elements.

### CODE REVIEW

File: packages/simple-schema/lib/content-assist/element-name.js [hunk 1]
```diff
@@ -51,7 +44,22 @@ function elementNameCompletion(elementNode, xssElement, prefix = "") {
...
+          element.namespace === namespace.uri
+      );
+      const possibleSuggestionsWithoutExistingSingular = applicableElements(
+        xssElement.elements,
+        elementNode.subElements,
+        possibleElements
+      );
+      const namespaceHasApplicableElements =
+        possibleSuggestionsWithoutExistingSingular.length > 0;
+      return !!namespace.prefix && namespaceHasApplicableElements;
```
Comment (bd82) [inline packages/simple-schema/lib/content-assist/element-name.js]: You are combining somewhat separate conditions here.
Maybe make a separate filtering (BEFORE) for ignoring the default namespace.

BTW I am going to change how namespaces are represented:
- clearer default namespace
- allow namespaces to be "deleted" according to XML Spec.
- Namespaces as Map instead of array

Maybe this change should be done after the namespaces refactoring as it would be a breaking change?

Comment (voicis) [reply packages/simple-schema/lib/content-assist/element-name.js]: I'll change this to use the new namespace representation.

If we filter default namespace before, then we have to loop over the list of namespaces twice, but if you are fine with that I can change this.

Comment (bd82) [reply packages/simple-schema/lib/content-assist/element-name.js]: I do not understand what you mean by filter default namespace.
See the key used for default namespace: https://github.com/sap/xml-tools/commit/f9f6fdc#diff-e58b8cf0909522d59cd0ebd69e9fd59aR49

**Comment by voicis** [comment]
Rebased on master. @bd82 are these the changes that you meant?

File: packages/simple-schema/test/content-assist/element-name-spec.js [hunk 2]
```diff
@@ -464,5 +489,165 @@ describe("The XML Simple Schema", () => {
...
+          text: "age"
+        },
+        {
+          label: "address",
+          text: "address"
+        }
+      ]);
+      expect(suggestions).to.have.lengthOf(3);
+    });
+    it("should not provide extraneous namespace prefixes for singular items", () => {
```
Comment (bd82) [inline packages/simple-schema/test/content-assist/element-name-spec.js]: empty line before new `it` please for readability

File: packages/simple-schema/test/content-assist/element-name-spec.js [hunk 3]
```diff
@@ -464,5 +489,165 @@ describe("The XML Simple Schema", () => {
       expect(suggestions).to.deep.include.members([]);
       expect(suggestions).to.have.lengthOf(0);
     });
```
Comment (bd82) [inline packages/simple-schema/test/content-assist/element-name-spec.js]: don't be shy on using line terminators :)

File: packages/simple-schema/test/content-assist/element-name-spec.js [hunk 4]
```diff
@@ -464,5 +489,165 @@ describe("The XML Simple Schema", () => {
...
+        {
+          label: "age",
+          text: "age"
+        },
+        {
+          label: "address",
+          text: "address"
+        }
+      ]);
+      expect(suggestions).to.have.lengthOf(3);
```
Comment (bd82) [inline packages/simple-schema/test/content-assist/element-name-spec.js]: test should **explicitly** state that the "abc" prefix is not expected.

Comment (bd82) [reply packages/simple-schema/test/content-assist/element-name-spec.js]: or at the minimum comment it

File: packages/simple-schema/test/content-assist/element-name-spec.js [hunk 5]
```diff
@@ -464,5 +489,165 @@ describe("The XML Simple Schema", () => {
...
```
Comment (bd82) [inline packages/simple-schema/test/content-assist/element-name-spec.js]: test should explicitly state that the "abc" prefix is not expected.
